
function(dnds_add_lib_fast LIBNAME CPPS LINKS)
    message("lib ${LIBNAME} CPPS is ${CPPS}")
    add_library(${LIBNAME} STATIC ${CPPS})
    target_include_directories(${LIBNAME} PUBLIC ${EXTERNAL_INCLUDES} PUBLIC ${INCLUDES})
    target_link_libraries(${LIBNAME} PUBLIC ${LINKS})
    if(DNDS_FAST_BUILD_FAST)
        if(LLVM OR MINGW OR UNIX)
            target_compile_options(${LIBNAME} PUBLIC -O3)
        elseif(WIN32 OR MSVC)
            # target_compile_options(${CPP_NAME_A} PUBLIC /O2)
            target_compile_options(${LIBNAME} PUBLIC -O3)
        else()
            message(FATAL_ERROR "NOT YET IMPLEMENTED HERE")
        endif()
    endif()
endfunction(dnds_add_lib_fast)

function(dnds_add_lib LIBNAME CPPS LINKS)
    message("lib ${LIBNAME} CPPS is ${CPPS}")
    add_library(${LIBNAME} STATIC ${CPPS})
    target_include_directories(${LIBNAME} PUBLIC ${EXTERNAL_INCLUDES} PUBLIC ${INCLUDES})
    target_link_libraries(${LIBNAME} PUBLIC ${LINKS})
endfunction(dnds_add_lib)
