
function(dnds_add_lib_fast LIBNAME CPPS LINKS)
    message("lib ${LIBNAME} CPPS is ${CPPS}")
    add_library(${LIBNAME} STATIC ${CPPS})
    target_include_directories(${LIBNAME} PRIVATE ${EXTERNAL_INCLUDES} PRIVATE ${INCLUDES})
    target_link_libraries(${LIBNAME} INTERFACE ${LINKS})
    if(DNDS_FAST_BUILD_FAST)
        if(LLVM OR MINGW OR UNIX)
            target_compile_options(${LIBNAME} PRIVATE -O3 -g0)
            if(${CMAKE_BUILD_TYPE} STREQUAL "Debug" AND ${DNDS_USE_NO_OMIT_FRAME_POINTER})
                target_compile_options(${LIBNAME} PRIVATE -fno-omit-frame-pointer)
            endif()
        elseif(WIN32 OR MSVC)
            # target_compile_options(${CPP_NAME_A} PRIVATE /O2)
            if(${CMAKE_CXX_COMPILER_ID} STREQUAL "MSVC")
                target_compile_options(${LIBNAME} PRIVATE /O2 /g0)
            else()
                target_compile_options(${LIBNAME} PRIVATE -O3 -g0)
            endif()
        else()
            message(FATAL_ERROR "NOT YET IMPLEMENTED HERE")
        endif()
    endif()
endfunction(dnds_add_lib_fast)

function(dnds_add_lib LIBNAME CPPS LINKS)
    message("lib ${LIBNAME} CPPS is ${CPPS}")
    add_library(${LIBNAME} STATIC ${CPPS})
    target_include_directories(${LIBNAME} PRIVATE ${EXTERNAL_INCLUDES} PRIVATE ${INCLUDES})
    target_link_libraries(${LIBNAME} INTERFACE ${LINKS})
endfunction(dnds_add_lib)
