"""Publication plotting helpers for DNDSR convergence histories."""

from .multigrid import (
    MultigridRunName,
    old_plot_selector,
    parse_multigrid_run_name,
)

from .series import (
    ReachResult,
    compute_residual_maxima,
    first_threshold_reach,
    load_dndsr_log,
    historical_wall_time,
    normalize_residual,
    prepare_series,
    startup_corrected_wall_time,
    windowed_std,
)
from .style import (
    A4_LANDSCAPE,
    A4_PORTRAIT,
    ARTICLE_LANDSCAPE,
    ARTICLE_PORTRAIT,
    COLORBLIND_COLORS,
    DEFAULT_MARKERS,
    DEFAULT_STYLE,
    LINE_STYLES,
    PublicationStyle,
    apply_publication_style,
    create_figure,
    finalize_axes,
    map_solver_name,
    marker_every_for_count,
    plot_one,
    save_figure,
    series_encoding,
)

__all__ = [
    "A4_LANDSCAPE",
    "A4_PORTRAIT",
    "ARTICLE_LANDSCAPE",
    "ARTICLE_PORTRAIT",
    "COLORBLIND_COLORS",
    "DEFAULT_MARKERS",
    "DEFAULT_STYLE",
    "LINE_STYLES",
    "MultigridRunName",
    "PublicationStyle",
    "ReachResult",
    "apply_publication_style",
    "compute_residual_maxima",
    "create_figure",
    "finalize_axes",
    "first_threshold_reach",
    "load_dndsr_log",
    "map_solver_name",
    "marker_every_for_count",
    "historical_wall_time",
    "normalize_residual",
    "old_plot_selector",
    "plot_one",
    "parse_multigrid_run_name",
    "prepare_series",
    "startup_corrected_wall_time",
    "save_figure",
    "series_encoding",
    "windowed_std",
]
